name = "cloudflare-playwright"
main = "src/index.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-03-14"
upload_source_maps = true

[browser]
binding = "MYBROWSER"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PlaywrightMCP"]

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "PlaywrightMCP"

[observability]
enabled = true
